name: Deploy dev-preview to Firebase Hosting
on:
  push:
    branches-ignore:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEARCHZONECH }}'
          projectId: searchzonech
          expires: 10d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
